### ISSUE TITLE
autoDeploy error

### ISSUE THREAD

**Issue by GhostWasFound13** [RainyXeon/Cylane#22]
![IMG_20230409_111512](https://user-images.githubusercontent.com/87599595/230754100-35827eb6-bd71-45c8-ac33-b7eedda619a8.jpg)
![IMG_20230409_111458](https://user-images.githubusercontent.com/87599595/230754102-7213eb65-df21-4625-a037-fa1cbedf95e1.jpg)
![IMG_20230409_111443](https://user-images.githubusercontent.com/87599595/230754106-544bbee8-b123-438d-a66b-68c92e260d32.jpg)
I dont know how to solve the error what its
discord.js version 14.8.0 
can you please fix the autoDeploy

**Comment by RainyXeon** [comment]
Can I have a full log file in `./logs` dir?

**Comment by RainyXeon** [comment]
@ghostLuna75 Do you have discord account? If have, DM me: RainyXeon </>#0017

**Comment by RainyXeon** [comment]
@ghostLuna75 can you DM me or give me your discord user name for sending file?
