### ISSUE TITLE
Profile bug 

### ISSUE THREAD

**Issue by ghostLuna75** [RainyXeon/Cylane#24]
![IMG_20230410_193332](https://user-images.githubusercontent.com/87599595/230903916-1d8a6f85-02d0-488b-b9a3-794d3c921747.jpg)
The error just this only no joke not that long

**Comment by RainyXeon** [comment]
Hot fixed on https://github.com/RainyXeon/Cylane/commit/c102834933a3c727ec0429ac9e8a955d39477b53 commit
