### ISSUE TITLE
After sharding on, the bot will join only a few voice channels. 

### ISSUE THREAD

**Issue by hash-xx** [RainyXeon/Cylane#28]
After sharding on, the bot will join only a few voice channels.  The bot will not join the voice channel even if the song is added to the queue as ads.

**Comment by RainyXeon** [comment]
Can you try to change from `mode: "process"` to `mode: "worker"` in `/src/client/sharding/index.js` file?

**Comment by hash-xx** [comment]
Yes, I changed that too. There was no difference. I put 2 clusters, 4
totshards and 2 shardsprecluster for this. Is there any other solution? May
I know if I am the only one having this problem?

**Comment by RainyXeon** [comment]
@hash-xx can you record your bug, cuz idk how it happened to you

**Comment by hash-xx** [comment]
2023-05-08 23-38-37.mp4
<https://drive.google.com/file/d/1WGUbkwDIjxumisK1OnBzs9obdgCmaNvH/view?usp=drive_web>
I have attached a video.  The player is created on some servers.  In some
servers, the player is not created.  How to fix this?
