### ISSUE TITLE
Stereo sound 

### ISSUE THREAD

**Issue by SashaXser** [RainyXeon/Cylane#3]
I want the bot to fuck my ears in stereo. pls
Is it possible to do so?

**Comment by RainyXeon** [comment]
Do you mean that make the bot run Stereo when you toggle it? Can you explain more clearly?

**Comment by SashaXser** [comment]
Yes, a separate option to turn on the stereo

**Comment by RainyXeon** [comment]
@SashaXser I will research it later.

**Comment by RainyXeon** [comment]
Closed due to no longer respond
