### ISSUE TITLE
interaction failed

### ISSUE THREAD

**Issue by Y345Developr** [RainyXeon/Cylane#30]
message: TypeError: Cannot read properties of undefined (reading 'send')
in Cylane-main\src\events\players\playerStart.js:203:30)
and Cylane-main\src\events\players\playerStart.js:245:30)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5),

**Comment by RainyXeon** [comment]
Now fixed in commit https://github.com/RainyXeon/Cylane/commit/61d72df76216e72265e64f11098d3ac2bac787ed
If still not working, make sure you set  `WEBSOCKET: false` and not modified the bot.
