### ISSUE TITLE
Unable to function properly

### ISSUE THREAD

**Issue by ANOPREMIUM** [RainyXeon/Cylane#37]
I am using the Container Manager (Docker) application in Synology NAS to run this project. I have successfully created three containers named "cylane," "mongodb," and "lavalink." Unfortunately, it is unable to run properly. When I see the status indicator light turn "green," it immediately changes to "black" in the next second, indicating that it is not functioning correctly. If you need any additional information, please let me know. Thank you.
 
 
<img width="895" alt="Snipaste_2023-06-30_17-48-33" src="https://github.com/RainyXeon/Cylane/assets/115340708/d8031ae6-609e-44dc-a062-a91b369647ba">
<img width="890" alt="Snipaste_2023-06-30_17-48-59" src="https://github.com/RainyXeon/Cylane/assets/115340708/14fae496-47da-4277-adb6-fb7f5ce62f7d">
<img width="900" alt="Snipaste_2023-06-30_17-49-34" src="https://github.com/RainyXeon/Cylane/assets/115340708/4bd7aed6-9165-49c3-b3e1-cf88dca3431b">

**Comment by ANOPREMIUM** [comment]
[log.zip](https://github.com/RainyXeon/Cylane/files/11915591/log.zip)

<img width="1282" alt="Snipaste_2023-06-30_18-49-30" src="https://github.com/RainyXeon/Cylane/assets/115340708/76040835-7488-41af-9383-fe12c323bb15">
<img width="1282" alt="Snipaste_2023-06-30_18-49-33" src="https://github.com/RainyXeon/Cylane/assets/115340708/870a1263-0f5e-4eb0-a327-a629862898c4">
<img width="1282" alt="Snipaste_2023-06-30_18-49-37" src="https://github.com/RainyXeon/Cylane/assets/115340708/a69c5a25-c8a9-49db-8d9c-bc91f400a65e">

**Comment by RainyXeon** [comment]
@ANOPREMIUM I have updated the config like in this commit https://github.com/RainyXeon/Cylane/commit/84b14c5eb7301d81d48b66f5beaaed0bfdc939ef . But like I see, you haven't config the `application.yml` file. So the sollution is config the `application.yml` and try again. The example here: https://github.com/RainyXeon/Cylane/blob/main/application.example.yml

**Comment by RainyXeon** [comment]
@ANOPREMIUM closed bc no respond
