### ISSUE TITLE
Uhhhhhh, why it's reading env instead of my yml file?

### ISSUE THREAD

**Issue by OrdinaryEnder** [RainyXeon/Cylane#44]
Got this error while running in Linux machine

```js
/root/Cylane/src/plugins/prase.js:36
      if (boolean.includes(process.env[matches[1]].trim().toLowerCase())) {
                                                   ^

TypeError: Cannot read properties of undefined (reading 'trim')
``|

**Comment by RainyXeon** [comment]
@OrdinaryEnder 
Can you check this commit?
https://github.com/RainyXeon/Cylane/tree/b2361f7af0813666f2d2e4079c063bbc8554b88e

**Comment by OrdinaryEnder** [comment]
> @OrdinaryEnder Can you check this commit? https://github.com/RainyXeon/Cylane/tree/b2361f7af0813666f2d2e4079c063bbc8554b88e

@RainyXeon it works cheers
