### ISSUE TITLE
I want a code autocomplete

### ISSUE THREAD

**Issue by NSystemx** [RainyXeon/Cylane#50]
![image](https://github.com/RainyXeon/Cylane/assets/148412879/5b286190-5f3e-4c26-90b3-bf4fc512ec38)

**Comment by NSystemx** [comment]
![image](https://github.com/RainyXeon/Cylane/assets/148412879/8c1e0472-3e68-4360-87d9-07a6e2e4e400)
Not Show

**Comment by RainyXeon** [comment]
@NSystemx Like it take a long time to load autocomplete and not response?

**Comment by RainyXeon** [comment]
@NSystemx Because the autocomplete is available in my bot for 1 years

**Comment by NSystemx** [comment]
I need the code, where is the file location?

**Comment by RainyXeon** [comment]
@NSystemx src/events/guild/interactionCreate.ts

**Comment by RainyXeon** [comment]
@NSystemx can u check this commit https://github.com/RainyXeon/Cylane/commit/19f989ebc7d0562bab2f5152464e7e18d0952bba to see if it's working?

**Comment by NSystemx** [comment]
I completely redid your bot. But I can't use autocomplete.

**Comment by NSystemx** [comment]
I had to redo it from the beginning. ( autocomplete )

**Comment by NSystemx** [comment]
how to

**Comment by RainyXeon** [comment]
@NSystemx idk how you can break that sys but maybe you should clone this repo and try again

**Comment by NSystemx** [comment]
I just want that feature, I just want to decode it.

**Comment by RainyXeon** [comment]
@NSystemx So you want that feature on your bot, right?
Like outside this repo?
