### ISSUE TITLE
24/7, Spotify Error!

### ISSUE THREAD

**Issue by ZoldZap** [RainyXeon/Cylane#52]
24/7 should stay always active, even after restart and bot should join voice channel automatically and continue playing music after restart, spotify links doesn't update setup channel's message.

**Comment by RainyXeon** [comment]
@ZoldNeverDie Like when u paste soptify short link and it won't queue your song, right?

**Comment by ZoldNeverDie** [comment]
@RainyXeon it does queue my song and even plays but the setup channel's message doesn't update.. like it doesn't show which dong it is playing right now.

**Comment by RainyXeon** [comment]
@ZoldNeverDie Ohhh ok, let me see..

**Comment by ZoldNeverDie** [comment]
@RainyXeon sure and thanks for fast replies.

**Comment by RainyXeon** [comment]
@ZoldNeverDie Can u check this commit?
https://github.com/RainyXeon/Cylane/tree/a5de7328b1a6d19081b168f66312523488cdf378

**Comment by ZoldNeverDie** [comment]
@RainyXeon working beautifully!

**Comment by ZoldNeverDie** [comment]
yes why not but what about the 24/7 and auto voice channel join if the bot restarts while playing music. @RainyXeon

**Comment by RainyXeon** [comment]
@ZoldNeverDie Like autoreconnect and play the previous music link?

**Comment by ZoldNeverDie** [comment]
@RainyXeon exactly

**Comment by ZoldNeverDie** [comment]
@RainyXeon u can set a prase application.yml if people want it or not.

**Comment by RainyXeon** [comment]
@ZoldNeverDie Ok, I guess

**Comment by RainyXeon** [comment]
Closed due no longer respond
