### ISSUE TITLE
/volume not working

### ISSUE THREAD

**Issue by SashaXser** [RainyXeon/Cylane#6]
Wow, another bug. Just stuck , but if use Player control mode he changes, but  1% goto 0.06% and lower

**Comment by RainyXeon** [comment]
Sorry for the inconvenience because I skipped the whole test case. Can you describe it more clearly?

**Comment by SashaXser** [comment]
> Sorry for the inconvenience because I skipped the whole test case. Can you describe it more clearly?

[Video](https://kappa.lol/v-fpE)

**Comment by RainyXeon** [comment]
@SashaXser Now fixed on https://github.com/RainyXeon/Cylane/commit/65f45b557ad2913e12ceed6b2864b09e3fabdbf2 commit
