### ISSUE TITLE
address already in use when using 2 clusters in sharding

### ISSUE THREAD

**Issue by CodingWithHardik** [RainyXeon/Cylane#7]

**Comment by CodingWithHardik** [comment]
@RainyXeon fix it

**Comment by CodingWithHardik** [comment]
@RainyXeon when it will be fixed ?

**Comment by RainyXeon** [comment]
@CodingWithHardik I'm not done yet, but you can use normal shard mode by using `npm run start:normal` command for avoid same address issue.

**Comment by CodingWithHardik** [comment]
@RainyXeon try to replace `port: this.config.PORT` to `noServer: true`

**Comment by CodingWithHardik** [comment]
I don't know but I think this will fix the issue

**Comment by CodingWithHardik** [comment]
its not working don't try

**Comment by RainyXeon** [comment]
@CodingWithHardik now fixed by block using ws in shard mode https://github.com/RainyXeon/Cylane/commit/689351871f96c2f6a6884807ad62f1097eefe129
